development:
  cloud_name: `{{process.env.CLOUDNAME}}`
  api_key: `{{process.env.CLOUDAPIKEY}}`
  api_secret: `{{process.env.CLOUDINARYSECRET}}`
  secure: true

production:
  cloud_name: `{{process.env.CLOUDNAME}}`
  api_key: `{{process.env.CLOUDAPIKEY}}`
  api_secret: `{{process.env.CLOUDINARYSECRET}}`
  secure: true
